// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/common/config_extrinsics.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "apollo_msgs/proto/common/config_extrinsics.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace common {
namespace config {

namespace {

const ::google::protobuf::Descriptor* Transform_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Transform_reflection_ = NULL;
const ::google::protobuf::Descriptor* Extrinsics_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Extrinsics_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() {
  protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "apollo_msgs/proto/common/config_extrinsics.proto");
  GOOGLE_CHECK(file != NULL);
  Transform_descriptor_ = file->message_type(0);
  static const int Transform_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, source_frame_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, target_frame_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, translation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, rotation_),
  };
  Transform_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Transform_descriptor_,
      Transform::default_instance_,
      Transform_offsets_,
      -1,
      -1,
      -1,
      sizeof(Transform),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, _is_default_instance_));
  Extrinsics_descriptor_ = file->message_type(1);
  static const int Extrinsics_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Extrinsics, tansforms_),
  };
  Extrinsics_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Extrinsics_descriptor_,
      Extrinsics::default_instance_,
      Extrinsics_offsets_,
      -1,
      -1,
      -1,
      sizeof(Extrinsics),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Extrinsics, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Extrinsics, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Transform_descriptor_, &Transform::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Extrinsics_descriptor_, &Extrinsics::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() {
  delete Transform::default_instance_;
  delete Transform_reflection_;
  delete Extrinsics::default_instance_;
  delete Extrinsics_reflection_;
}

void protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::apollo::common::protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fgeometry_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n0apollo_msgs/proto/common/config_extrin"
    "sics.proto\022\024apollo.common.config\032\'apollo"
    "_msgs/proto/common/geometry.proto\"\221\001\n\tTr"
    "ansform\022\024\n\014source_frame\030\001 \001(\014\022\024\n\014target_"
    "frame\030\002 \001(\014\022+\n\013translation\030\003 \001(\0132\026.apoll"
    "o.common.Point3D\022+\n\010rotation\030\004 \001(\0132\031.apo"
    "llo.common.Quaternion\"@\n\nExtrinsics\0222\n\tt"
    "ansforms\030\001 \003(\0132\037.apollo.common.config.Tr"
    "ansformb\006proto3", 335);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "apollo_msgs/proto/common/config_extrinsics.proto", &protobuf_RegisterTypes);
  Transform::default_instance_ = new Transform();
  Extrinsics::default_instance_ = new Extrinsics();
  Transform::default_instance_->InitAsDefaultInstance();
  Extrinsics::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto {
  StaticDescriptorInitializer_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto() {
    protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto();
  }
} static_descriptor_initializer_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Transform::kSourceFrameFieldNumber;
const int Transform::kTargetFrameFieldNumber;
const int Transform::kTranslationFieldNumber;
const int Transform::kRotationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Transform::Transform()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.common.config.Transform)
}

void Transform::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  translation_ = const_cast< ::apollo::common::Point3D*>(&::apollo::common::Point3D::default_instance());
  rotation_ = const_cast< ::apollo::common::Quaternion*>(&::apollo::common::Quaternion::default_instance());
}

Transform::Transform(const Transform& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.common.config.Transform)
}

void Transform::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  source_frame_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_frame_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  translation_ = NULL;
  rotation_ = NULL;
}

Transform::~Transform() {
  // @@protoc_insertion_point(destructor:apollo.common.config.Transform)
  SharedDtor();
}

void Transform::SharedDtor() {
  source_frame_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_frame_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete translation_;
    delete rotation_;
  }
}

void Transform::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Transform::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Transform_descriptor_;
}

const Transform& Transform::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto();
  return *default_instance_;
}

Transform* Transform::default_instance_ = NULL;

Transform* Transform::New(::google::protobuf::Arena* arena) const {
  Transform* n = new Transform;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Transform::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.common.config.Transform)
  source_frame_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  target_frame_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) delete translation_;
  translation_ = NULL;
  if (GetArenaNoVirtual() == NULL && rotation_ != NULL) delete rotation_;
  rotation_ = NULL;
}

bool Transform::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.common.config.Transform)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes source_frame = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_source_frame()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_target_frame;
        break;
      }

      // optional bytes target_frame = 2;
      case 2: {
        if (tag == 18) {
         parse_target_frame:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_target_frame()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_translation;
        break;
      }

      // optional .apollo.common.Point3D translation = 3;
      case 3: {
        if (tag == 26) {
         parse_translation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_translation()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_rotation;
        break;
      }

      // optional .apollo.common.Quaternion rotation = 4;
      case 4: {
        if (tag == 34) {
         parse_rotation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rotation()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.common.config.Transform)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.common.config.Transform)
  return false;
#undef DO_
}

void Transform::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.common.config.Transform)
  // optional bytes source_frame = 1;
  if (this->source_frame().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->source_frame(), output);
  }

  // optional bytes target_frame = 2;
  if (this->target_frame().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->target_frame(), output);
  }

  // optional .apollo.common.Point3D translation = 3;
  if (this->has_translation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->translation_, output);
  }

  // optional .apollo.common.Quaternion rotation = 4;
  if (this->has_rotation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->rotation_, output);
  }

  // @@protoc_insertion_point(serialize_end:apollo.common.config.Transform)
}

::google::protobuf::uint8* Transform::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.common.config.Transform)
  // optional bytes source_frame = 1;
  if (this->source_frame().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->source_frame(), target);
  }

  // optional bytes target_frame = 2;
  if (this->target_frame().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->target_frame(), target);
  }

  // optional .apollo.common.Point3D translation = 3;
  if (this->has_translation()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->translation_, false, target);
  }

  // optional .apollo.common.Quaternion rotation = 4;
  if (this->has_rotation()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->rotation_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:apollo.common.config.Transform)
  return target;
}

int Transform::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.common.config.Transform)
  int total_size = 0;

  // optional bytes source_frame = 1;
  if (this->source_frame().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->source_frame());
  }

  // optional bytes target_frame = 2;
  if (this->target_frame().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->target_frame());
  }

  // optional .apollo.common.Point3D translation = 3;
  if (this->has_translation()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->translation_);
  }

  // optional .apollo.common.Quaternion rotation = 4;
  if (this->has_rotation()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->rotation_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transform::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.common.config.Transform)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Transform* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Transform>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.common.config.Transform)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.common.config.Transform)
    MergeFrom(*source);
  }
}

void Transform::MergeFrom(const Transform& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.common.config.Transform)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.source_frame().size() > 0) {

    source_frame_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_frame_);
  }
  if (from.target_frame().size() > 0) {

    target_frame_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.target_frame_);
  }
  if (from.has_translation()) {
    mutable_translation()->::apollo::common::Point3D::MergeFrom(from.translation());
  }
  if (from.has_rotation()) {
    mutable_rotation()->::apollo::common::Quaternion::MergeFrom(from.rotation());
  }
}

void Transform::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.common.config.Transform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Transform::CopyFrom(const Transform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.common.config.Transform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transform::IsInitialized() const {

  return true;
}

void Transform::Swap(Transform* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Transform::InternalSwap(Transform* other) {
  source_frame_.Swap(&other->source_frame_);
  target_frame_.Swap(&other->target_frame_);
  std::swap(translation_, other->translation_);
  std::swap(rotation_, other->rotation_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Transform::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Transform_descriptor_;
  metadata.reflection = Transform_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Transform

// optional bytes source_frame = 1;
void Transform::clear_source_frame() {
  source_frame_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Transform::source_frame() const {
  // @@protoc_insertion_point(field_get:apollo.common.config.Transform.source_frame)
  return source_frame_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transform::set_source_frame(const ::std::string& value) {
  
  source_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.common.config.Transform.source_frame)
}
 void Transform::set_source_frame(const char* value) {
  
  source_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.common.config.Transform.source_frame)
}
 void Transform::set_source_frame(const void* value, size_t size) {
  
  source_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.common.config.Transform.source_frame)
}
 ::std::string* Transform::mutable_source_frame() {
  
  // @@protoc_insertion_point(field_mutable:apollo.common.config.Transform.source_frame)
  return source_frame_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Transform::release_source_frame() {
  // @@protoc_insertion_point(field_release:apollo.common.config.Transform.source_frame)
  
  return source_frame_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transform::set_allocated_source_frame(::std::string* source_frame) {
  if (source_frame != NULL) {
    
  } else {
    
  }
  source_frame_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_frame);
  // @@protoc_insertion_point(field_set_allocated:apollo.common.config.Transform.source_frame)
}

// optional bytes target_frame = 2;
void Transform::clear_target_frame() {
  target_frame_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Transform::target_frame() const {
  // @@protoc_insertion_point(field_get:apollo.common.config.Transform.target_frame)
  return target_frame_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transform::set_target_frame(const ::std::string& value) {
  
  target_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.common.config.Transform.target_frame)
}
 void Transform::set_target_frame(const char* value) {
  
  target_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.common.config.Transform.target_frame)
}
 void Transform::set_target_frame(const void* value, size_t size) {
  
  target_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.common.config.Transform.target_frame)
}
 ::std::string* Transform::mutable_target_frame() {
  
  // @@protoc_insertion_point(field_mutable:apollo.common.config.Transform.target_frame)
  return target_frame_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Transform::release_target_frame() {
  // @@protoc_insertion_point(field_release:apollo.common.config.Transform.target_frame)
  
  return target_frame_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transform::set_allocated_target_frame(::std::string* target_frame) {
  if (target_frame != NULL) {
    
  } else {
    
  }
  target_frame_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_frame);
  // @@protoc_insertion_point(field_set_allocated:apollo.common.config.Transform.target_frame)
}

// optional .apollo.common.Point3D translation = 3;
bool Transform::has_translation() const {
  return !_is_default_instance_ && translation_ != NULL;
}
void Transform::clear_translation() {
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) delete translation_;
  translation_ = NULL;
}
const ::apollo::common::Point3D& Transform::translation() const {
  // @@protoc_insertion_point(field_get:apollo.common.config.Transform.translation)
  return translation_ != NULL ? *translation_ : *default_instance_->translation_;
}
::apollo::common::Point3D* Transform::mutable_translation() {
  
  if (translation_ == NULL) {
    translation_ = new ::apollo::common::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:apollo.common.config.Transform.translation)
  return translation_;
}
::apollo::common::Point3D* Transform::release_translation() {
  // @@protoc_insertion_point(field_release:apollo.common.config.Transform.translation)
  
  ::apollo::common::Point3D* temp = translation_;
  translation_ = NULL;
  return temp;
}
void Transform::set_allocated_translation(::apollo::common::Point3D* translation) {
  delete translation_;
  translation_ = translation;
  if (translation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.common.config.Transform.translation)
}

// optional .apollo.common.Quaternion rotation = 4;
bool Transform::has_rotation() const {
  return !_is_default_instance_ && rotation_ != NULL;
}
void Transform::clear_rotation() {
  if (GetArenaNoVirtual() == NULL && rotation_ != NULL) delete rotation_;
  rotation_ = NULL;
}
const ::apollo::common::Quaternion& Transform::rotation() const {
  // @@protoc_insertion_point(field_get:apollo.common.config.Transform.rotation)
  return rotation_ != NULL ? *rotation_ : *default_instance_->rotation_;
}
::apollo::common::Quaternion* Transform::mutable_rotation() {
  
  if (rotation_ == NULL) {
    rotation_ = new ::apollo::common::Quaternion;
  }
  // @@protoc_insertion_point(field_mutable:apollo.common.config.Transform.rotation)
  return rotation_;
}
::apollo::common::Quaternion* Transform::release_rotation() {
  // @@protoc_insertion_point(field_release:apollo.common.config.Transform.rotation)
  
  ::apollo::common::Quaternion* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
void Transform::set_allocated_rotation(::apollo::common::Quaternion* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.common.config.Transform.rotation)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Extrinsics::kTansformsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Extrinsics::Extrinsics()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.common.config.Extrinsics)
}

void Extrinsics::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Extrinsics::Extrinsics(const Extrinsics& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.common.config.Extrinsics)
}

void Extrinsics::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

Extrinsics::~Extrinsics() {
  // @@protoc_insertion_point(destructor:apollo.common.config.Extrinsics)
  SharedDtor();
}

void Extrinsics::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Extrinsics::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Extrinsics::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Extrinsics_descriptor_;
}

const Extrinsics& Extrinsics::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_apollo_5fmsgs_2fproto_2fcommon_2fconfig_5fextrinsics_2eproto();
  return *default_instance_;
}

Extrinsics* Extrinsics::default_instance_ = NULL;

Extrinsics* Extrinsics::New(::google::protobuf::Arena* arena) const {
  Extrinsics* n = new Extrinsics;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Extrinsics::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.common.config.Extrinsics)
  tansforms_.Clear();
}

bool Extrinsics::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.common.config.Extrinsics)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.common.config.Transform tansforms = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_tansforms:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_tansforms()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_tansforms;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.common.config.Extrinsics)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.common.config.Extrinsics)
  return false;
#undef DO_
}

void Extrinsics::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.common.config.Extrinsics)
  // repeated .apollo.common.config.Transform tansforms = 1;
  for (unsigned int i = 0, n = this->tansforms_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->tansforms(i), output);
  }

  // @@protoc_insertion_point(serialize_end:apollo.common.config.Extrinsics)
}

::google::protobuf::uint8* Extrinsics::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.common.config.Extrinsics)
  // repeated .apollo.common.config.Transform tansforms = 1;
  for (unsigned int i = 0, n = this->tansforms_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->tansforms(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:apollo.common.config.Extrinsics)
  return target;
}

int Extrinsics::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.common.config.Extrinsics)
  int total_size = 0;

  // repeated .apollo.common.config.Transform tansforms = 1;
  total_size += 1 * this->tansforms_size();
  for (int i = 0; i < this->tansforms_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tansforms(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Extrinsics::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.common.config.Extrinsics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Extrinsics* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Extrinsics>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.common.config.Extrinsics)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.common.config.Extrinsics)
    MergeFrom(*source);
  }
}

void Extrinsics::MergeFrom(const Extrinsics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.common.config.Extrinsics)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  tansforms_.MergeFrom(from.tansforms_);
}

void Extrinsics::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.common.config.Extrinsics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extrinsics::CopyFrom(const Extrinsics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.common.config.Extrinsics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extrinsics::IsInitialized() const {

  return true;
}

void Extrinsics::Swap(Extrinsics* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Extrinsics::InternalSwap(Extrinsics* other) {
  tansforms_.UnsafeArenaSwap(&other->tansforms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Extrinsics::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Extrinsics_descriptor_;
  metadata.reflection = Extrinsics_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Extrinsics

// repeated .apollo.common.config.Transform tansforms = 1;
int Extrinsics::tansforms_size() const {
  return tansforms_.size();
}
void Extrinsics::clear_tansforms() {
  tansforms_.Clear();
}
const ::apollo::common::config::Transform& Extrinsics::tansforms(int index) const {
  // @@protoc_insertion_point(field_get:apollo.common.config.Extrinsics.tansforms)
  return tansforms_.Get(index);
}
::apollo::common::config::Transform* Extrinsics::mutable_tansforms(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.common.config.Extrinsics.tansforms)
  return tansforms_.Mutable(index);
}
::apollo::common::config::Transform* Extrinsics::add_tansforms() {
  // @@protoc_insertion_point(field_add:apollo.common.config.Extrinsics.tansforms)
  return tansforms_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::common::config::Transform >*
Extrinsics::mutable_tansforms() {
  // @@protoc_insertion_point(field_mutable_list:apollo.common.config.Extrinsics.tansforms)
  return &tansforms_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::common::config::Transform >&
Extrinsics::tansforms() const {
  // @@protoc_insertion_point(field_list:apollo.common.config.Extrinsics.tansforms)
  return tansforms_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace config
}  // namespace common
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
