// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/localization/gps.proto

#ifndef PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto__INCLUDED
#define PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "apollo_msgs/proto/common/header.pb.h"
#include "apollo_msgs/proto/localization/pose.pb.h"
// @@protoc_insertion_point(includes)

namespace apollo {
namespace localization {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();
void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();
void protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();

class Gps;

// ===================================================================

class Gps : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.Gps) */ {
 public:
  Gps();
  virtual ~Gps();

  Gps(const Gps& from);

  inline Gps& operator=(const Gps& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Gps& default_instance();

  void Swap(Gps* other);

  // implements Message ----------------------------------------------

  inline Gps* New() const { return New(NULL); }

  Gps* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Gps& from);
  void MergeFrom(const Gps& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Gps* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.localization.Pose localization = 2;
  bool has_localization() const;
  void clear_localization();
  static const int kLocalizationFieldNumber = 2;
  const ::apollo::localization::Pose& localization() const;
  ::apollo::localization::Pose* mutable_localization();
  ::apollo::localization::Pose* release_localization();
  void set_allocated_localization(::apollo::localization::Pose* localization);

  // @@protoc_insertion_point(class_scope:apollo.localization.Gps)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::apollo::common::Header* header_;
  ::apollo::localization::Pose* localization_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();
  friend void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();
  friend void protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto();

  void InitAsDefaultInstance();
  static Gps* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Gps

// optional .apollo.common.Header header = 1;
inline bool Gps::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
inline void Gps::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
inline const ::apollo::common::Header& Gps::header() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Gps.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* Gps::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.localization.Gps.header)
  return header_;
}
inline ::apollo::common::Header* Gps::release_header() {
  // @@protoc_insertion_point(field_release:apollo.localization.Gps.header)
  
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Gps::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Gps.header)
}

// optional .apollo.localization.Pose localization = 2;
inline bool Gps::has_localization() const {
  return !_is_default_instance_ && localization_ != NULL;
}
inline void Gps::clear_localization() {
  if (GetArenaNoVirtual() == NULL && localization_ != NULL) delete localization_;
  localization_ = NULL;
}
inline const ::apollo::localization::Pose& Gps::localization() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Gps.localization)
  return localization_ != NULL ? *localization_ : *default_instance_->localization_;
}
inline ::apollo::localization::Pose* Gps::mutable_localization() {
  
  if (localization_ == NULL) {
    localization_ = new ::apollo::localization::Pose;
  }
  // @@protoc_insertion_point(field_mutable:apollo.localization.Gps.localization)
  return localization_;
}
inline ::apollo::localization::Pose* Gps::release_localization() {
  // @@protoc_insertion_point(field_release:apollo.localization.Gps.localization)
  
  ::apollo::localization::Pose* temp = localization_;
  localization_ = NULL;
  return temp;
}
inline void Gps::set_allocated_localization(::apollo::localization::Pose* localization) {
  delete localization_;
  localization_ = localization;
  if (localization) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Gps.localization)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace localization
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2fgps_2eproto__INCLUDED
