// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/localization/localization_config.proto

#ifndef PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto__INCLUDED
#define PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace localization {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();
void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();
void protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();

class LocalizationConfig;

enum LocalizationConfig_LocalizationType {
  LocalizationConfig_LocalizationType_RTK = 0,
  LocalizationConfig_LocalizationType_CAMERA = 1,
  LocalizationConfig_LocalizationType_LocalizationConfig_LocalizationType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LocalizationConfig_LocalizationType_LocalizationConfig_LocalizationType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LocalizationConfig_LocalizationType_IsValid(int value);
const LocalizationConfig_LocalizationType LocalizationConfig_LocalizationType_LocalizationType_MIN = LocalizationConfig_LocalizationType_RTK;
const LocalizationConfig_LocalizationType LocalizationConfig_LocalizationType_LocalizationType_MAX = LocalizationConfig_LocalizationType_CAMERA;
const int LocalizationConfig_LocalizationType_LocalizationType_ARRAYSIZE = LocalizationConfig_LocalizationType_LocalizationType_MAX + 1;

const ::google::protobuf::EnumDescriptor* LocalizationConfig_LocalizationType_descriptor();
inline const ::std::string& LocalizationConfig_LocalizationType_Name(LocalizationConfig_LocalizationType value) {
  return ::google::protobuf::internal::NameOfEnum(
    LocalizationConfig_LocalizationType_descriptor(), value);
}
inline bool LocalizationConfig_LocalizationType_Parse(
    const ::std::string& name, LocalizationConfig_LocalizationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LocalizationConfig_LocalizationType>(
    LocalizationConfig_LocalizationType_descriptor(), name, value);
}
// ===================================================================

class LocalizationConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.LocalizationConfig) */ {
 public:
  LocalizationConfig();
  virtual ~LocalizationConfig();

  LocalizationConfig(const LocalizationConfig& from);

  inline LocalizationConfig& operator=(const LocalizationConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalizationConfig& default_instance();

  void Swap(LocalizationConfig* other);

  // implements Message ----------------------------------------------

  inline LocalizationConfig* New() const { return New(NULL); }

  LocalizationConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LocalizationConfig& from);
  void MergeFrom(const LocalizationConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LocalizationConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LocalizationConfig_LocalizationType LocalizationType;
  static const LocalizationType RTK =
    LocalizationConfig_LocalizationType_RTK;
  static const LocalizationType CAMERA =
    LocalizationConfig_LocalizationType_CAMERA;
  static inline bool LocalizationType_IsValid(int value) {
    return LocalizationConfig_LocalizationType_IsValid(value);
  }
  static const LocalizationType LocalizationType_MIN =
    LocalizationConfig_LocalizationType_LocalizationType_MIN;
  static const LocalizationType LocalizationType_MAX =
    LocalizationConfig_LocalizationType_LocalizationType_MAX;
  static const int LocalizationType_ARRAYSIZE =
    LocalizationConfig_LocalizationType_LocalizationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  LocalizationType_descriptor() {
    return LocalizationConfig_LocalizationType_descriptor();
  }
  static inline const ::std::string& LocalizationType_Name(LocalizationType value) {
    return LocalizationConfig_LocalizationType_Name(value);
  }
  static inline bool LocalizationType_Parse(const ::std::string& name,
      LocalizationType* value) {
    return LocalizationConfig_LocalizationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .apollo.localization.LocalizationConfig.LocalizationType localization_type = 1;
  void clear_localization_type();
  static const int kLocalizationTypeFieldNumber = 1;
  ::apollo::localization::LocalizationConfig_LocalizationType localization_type() const;
  void set_localization_type(::apollo::localization::LocalizationConfig_LocalizationType value);

  // @@protoc_insertion_point(class_scope:apollo.localization.LocalizationConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int localization_type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();
  friend void protobuf_AssignDesc_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static LocalizationConfig* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LocalizationConfig

// optional .apollo.localization.LocalizationConfig.LocalizationType localization_type = 1;
inline void LocalizationConfig::clear_localization_type() {
  localization_type_ = 0;
}
inline ::apollo::localization::LocalizationConfig_LocalizationType LocalizationConfig::localization_type() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationConfig.localization_type)
  return static_cast< ::apollo::localization::LocalizationConfig_LocalizationType >(localization_type_);
}
inline void LocalizationConfig::set_localization_type(::apollo::localization::LocalizationConfig_LocalizationType value) {
  
  localization_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationConfig.localization_type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace localization
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::localization::LocalizationConfig_LocalizationType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::LocalizationConfig_LocalizationType>() {
  return ::apollo::localization::LocalizationConfig_LocalizationType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto__INCLUDED
